// small_tree: base class to handle reduced tree ntuples
// File generated with generate_small_tree.exe

#ifndef H_SMALL_TREE
#define H_SMALL_TREE

#include <vector>
#include <string>

#include "TTree.h"
#include "TChain.h"

class small_tree{
public:
  small_tree(); // Constructor to create tree
  small_tree(const std::string &filename); // Constructor to read tree

  int Add(const std::string &filename);
  long GetEntries() const;
  virtual void GetEntry(const long entry);

  virtual void Fill();
  void Write();

  virtual std::string Type() const;

  static const double bad_val_;

  virtual ~small_tree();

  float const & dphi_wlep() const;
  float & dphi_wlep();
  float const & dphi_wlep_reliso() const;
  float & dphi_wlep_reliso();
  float const & ht() const;
  float & ht();
  float const & lep_pt() const;
  float & lep_pt();
  float const & lep_pt_reliso() const;
  float & lep_pt_reliso();
  float const & met() const;
  float & met();
  float const & met_phi() const;
  float & met_phi();
  float const & mht() const;
  float & mht();
  float const & min_mt_bmet() const;
  float & min_mt_bmet();
  float const & min_mt_bmet_with_w_mass() const;
  float & min_mt_bmet_with_w_mass();
  float const & mindphin_metjet() const;
  float & mindphin_metjet();
  float const & mj() const;
  float & mj();
  float const & mt() const;
  float & mt();
  float const & mt_reliso() const;
  float & mt_reliso();
  float const & ntrupv_mean() const;
  float & ntrupv_mean();
  float const & st() const;
  float & st();
  float const & st_reliso() const;
  float & st_reliso();
  float const & weight() const;
  float & weight();
  int const & event() const;
  int & event();
  int const & lumiblock() const;
  int & lumiblock();
  int const & nbl() const;
  int & nbl();
  int const & nbm() const;
  int & nbm();
  int const & nbt() const;
  int & nbt();
  int const & nels() const;
  int & nels();
  int const & nels_reliso() const;
  int & nels_reliso();
  int const & nfjets() const;
  int & nfjets();
  int const & njets() const;
  int & njets();
  int const & nleps() const;
  int & nleps();
  int const & nleps_reliso() const;
  int & nleps_reliso();
  int const & nmus() const;
  int & nmus();
  int const & nmus_reliso() const;
  int & nmus_reliso();
  int const & npv() const;
  int & npv();
  int const & ntks() const;
  int & ntks();
  int const & ntks_chg() const;
  int & ntks_chg();
  int const & ntks_chg_reliso() const;
  int & ntks_chg_reliso();
  int const & ntrupv() const;
  int & ntrupv();
  int const & nvels() const;
  int & nvels();
  int const & nvels_reliso() const;
  int & nvels_reliso();
  int const & nvmus() const;
  int & nvmus();
  int const & nvmus_reliso() const;
  int & nvmus_reliso();
  int const & run() const;
  int & run();
  std::vector<bool> const & els_ispf() const;
  std::vector<bool> & els_ispf();
  std::vector<bool> const & els_sigid() const;
  std::vector<bool> & els_sigid();
  std::vector<bool> const & els_tru_tm() const;
  std::vector<bool> & els_tru_tm();
  std::vector<bool> const & mus_sigid() const;
  std::vector<bool> & mus_sigid();
  std::vector<bool> const & mus_tru_tm() const;
  std::vector<bool> & mus_tru_tm();
  std::vector<bool> const & tks_from_tau() const;
  std::vector<bool> & tks_from_tau();
  std::vector<bool> const & tks_from_tauhad() const;
  std::vector<bool> & tks_from_tauhad();
  std::vector<bool> const & tks_from_taulep() const;
  std::vector<bool> & tks_from_taulep();
  std::vector<bool> const & tks_from_w() const;
  std::vector<bool> & tks_from_w();
  std::vector<bool> const & tks_is_primary() const;
  std::vector<bool> & tks_is_primary();
  std::vector<bool> const & tks_is_primary_reliso() const;
  std::vector<bool> & tks_is_primary_reliso();
  std::vector<bool> const & tks_is_sig_lep() const;
  std::vector<bool> & tks_is_sig_lep();
  std::vector<float> const & els_d0() const;
  std::vector<float> & els_d0();
  std::vector<float> const & els_dz() const;
  std::vector<float> & els_dz();
  std::vector<float> const & els_eta() const;
  std::vector<float> & els_eta();
  std::vector<float> const & els_miniso_10() const;
  std::vector<float> & els_miniso_10();
  std::vector<float> const & els_miniso_10_ch() const;
  std::vector<float> & els_miniso_10_ch();
  std::vector<float> const & els_miniso_10_pfpu() const;
  std::vector<float> & els_miniso_10_pfpu();
  std::vector<float> const & els_miniso_tr10() const;
  std::vector<float> & els_miniso_tr10();
  std::vector<float> const & els_miniso_tr10_ch() const;
  std::vector<float> & els_miniso_tr10_ch();
  std::vector<float> const & els_miniso_tr10_pfpu() const;
  std::vector<float> & els_miniso_tr10_pfpu();
  std::vector<float> const & els_mt() const;
  std::vector<float> & els_mt();
  std::vector<float> const & els_phi() const;
  std::vector<float> & els_phi();
  std::vector<float> const & els_pt() const;
  std::vector<float> & els_pt();
  std::vector<float> const & els_reliso() const;
  std::vector<float> & els_reliso();
  std::vector<float> const & els_reliso_r01() const;
  std::vector<float> & els_reliso_r01();
  std::vector<float> const & els_reliso_r015() const;
  std::vector<float> & els_reliso_r015();
  std::vector<float> const & els_reliso_r02() const;
  std::vector<float> & els_reliso_r02();
  std::vector<float> const & els_reliso_r03() const;
  std::vector<float> & els_reliso_r03();
  std::vector<float> const & els_reliso_r04() const;
  std::vector<float> & els_reliso_r04();
  std::vector<float> const & els_tru_dr() const;
  std::vector<float> & els_tru_dr();
  std::vector<float> const & fjets_eta() const;
  std::vector<float> & fjets_eta();
  std::vector<float> const & fjets_m() const;
  std::vector<float> & fjets_m();
  std::vector<float> const & fjets_nconst() const;
  std::vector<float> & fjets_nconst();
  std::vector<float> const & fjets_phi() const;
  std::vector<float> & fjets_phi();
  std::vector<float> const & fjets_pt() const;
  std::vector<float> & fjets_pt();
  std::vector<float> const & jets_csv() const;
  std::vector<float> & jets_csv();
  std::vector<float> const & jets_eta() const;
  std::vector<float> & jets_eta();
  std::vector<float> const & jets_id() const;
  std::vector<float> & jets_id();
  std::vector<float> const & jets_islep() const;
  std::vector<float> & jets_islep();
  std::vector<float> const & jets_phi() const;
  std::vector<float> & jets_phi();
  std::vector<float> const & jets_pt() const;
  std::vector<float> & jets_pt();
  std::vector<float> const & mc_eta() const;
  std::vector<float> & mc_eta();
  std::vector<float> const & mc_phi() const;
  std::vector<float> & mc_phi();
  std::vector<float> const & mc_pt() const;
  std::vector<float> & mc_pt();
  std::vector<float> const & mus_d0() const;
  std::vector<float> & mus_d0();
  std::vector<float> const & mus_dz() const;
  std::vector<float> & mus_dz();
  std::vector<float> const & mus_eta() const;
  std::vector<float> & mus_eta();
  std::vector<float> const & mus_miniso_10() const;
  std::vector<float> & mus_miniso_10();
  std::vector<float> const & mus_miniso_10_ch() const;
  std::vector<float> & mus_miniso_10_ch();
  std::vector<float> const & mus_miniso_10_pfpu() const;
  std::vector<float> & mus_miniso_10_pfpu();
  std::vector<float> const & mus_miniso_tr10() const;
  std::vector<float> & mus_miniso_tr10();
  std::vector<float> const & mus_miniso_tr10_ch() const;
  std::vector<float> & mus_miniso_tr10_ch();
  std::vector<float> const & mus_miniso_tr10_pfpu() const;
  std::vector<float> & mus_miniso_tr10_pfpu();
  std::vector<float> const & mus_mt() const;
  std::vector<float> & mus_mt();
  std::vector<float> const & mus_phi() const;
  std::vector<float> & mus_phi();
  std::vector<float> const & mus_pt() const;
  std::vector<float> & mus_pt();
  std::vector<float> const & mus_reliso() const;
  std::vector<float> & mus_reliso();
  std::vector<float> const & mus_reliso_r01() const;
  std::vector<float> & mus_reliso_r01();
  std::vector<float> const & mus_reliso_r015() const;
  std::vector<float> & mus_reliso_r015();
  std::vector<float> const & mus_reliso_r02() const;
  std::vector<float> & mus_reliso_r02();
  std::vector<float> const & mus_reliso_r03() const;
  std::vector<float> & mus_reliso_r03();
  std::vector<float> const & mus_reliso_r04() const;
  std::vector<float> & mus_reliso_r04();
  std::vector<float> const & mus_tru_dr() const;
  std::vector<float> & mus_tru_dr();
  std::vector<float> const & tks_eta() const;
  std::vector<float> & tks_eta();
  std::vector<float> const & tks_mini_ch() const;
  std::vector<float> & tks_mini_ch();
  std::vector<float> const & tks_mini_ne() const;
  std::vector<float> & tks_mini_ne();
  std::vector<float> const & tks_mt() const;
  std::vector<float> & tks_mt();
  std::vector<float> const & tks_phi() const;
  std::vector<float> & tks_phi();
  std::vector<float> const & tks_pt() const;
  std::vector<float> & tks_pt();
  std::vector<float> const & tks_r02_ch() const;
  std::vector<float> & tks_r02_ch();
  std::vector<float> const & tks_r02_ne() const;
  std::vector<float> & tks_r02_ne();
  std::vector<float> const & tks_r03_ch() const;
  std::vector<float> & tks_r03_ch();
  std::vector<float> const & tks_r03_ne() const;
  std::vector<float> & tks_r03_ne();
  std::vector<float> const & tks_tru_dp() const;
  std::vector<float> & tks_tru_dp();
  std::vector<float> const & tks_tru_dr() const;
  std::vector<float> & tks_tru_dr();
  std::vector<int> const & els_charge() const;
  std::vector<int> & els_charge();
  std::vector<int> const & els_tru_id() const;
  std::vector<int> & els_tru_id();
  std::vector<int> const & els_tru_momid() const;
  std::vector<int> & els_tru_momid();
  std::vector<int> const & mc_id() const;
  std::vector<int> & mc_id();
  std::vector<int> const & mc_status() const;
  std::vector<int> & mc_status();
  std::vector<int> const & mus_charge() const;
  std::vector<int> & mus_charge();
  std::vector<int> const & mus_tru_id() const;
  std::vector<int> & mus_tru_id();
  std::vector<int> const & mus_tru_momid() const;
  std::vector<int> & mus_tru_momid();
  std::vector<int> const & tks_from_pv() const;
  std::vector<int> & tks_from_pv();
  std::vector<int> const & tks_id() const;
  std::vector<int> & tks_id();
  std::vector<int> const & tks_num_prongs() const;
  std::vector<int> & tks_num_prongs();
  std::vector<int> const & tks_tru_id() const;
  std::vector<int> & tks_tru_id();
  std::vector<size_t> const & mc_mom() const;
  std::vector<size_t> & mc_mom();
  unsigned const & mc_type() const;
  unsigned & mc_type();


protected:
  TChain chain_;
  TTree tree_;
  long entry_;
  const bool read_only_;

private:
  class VectorLoader{
  public:
    VectorLoader();
  private:
    static bool loaded_;
  };

  static VectorLoader vl_;
  float dphi_wlep_;
  TBranch *b_dphi_wlep_;
  mutable bool c_dphi_wlep_;
  float dphi_wlep_reliso_;
  TBranch *b_dphi_wlep_reliso_;
  mutable bool c_dphi_wlep_reliso_;
  float ht_;
  TBranch *b_ht_;
  mutable bool c_ht_;
  float lep_pt_;
  TBranch *b_lep_pt_;
  mutable bool c_lep_pt_;
  float lep_pt_reliso_;
  TBranch *b_lep_pt_reliso_;
  mutable bool c_lep_pt_reliso_;
  float met_;
  TBranch *b_met_;
  mutable bool c_met_;
  float met_phi_;
  TBranch *b_met_phi_;
  mutable bool c_met_phi_;
  float mht_;
  TBranch *b_mht_;
  mutable bool c_mht_;
  float min_mt_bmet_;
  TBranch *b_min_mt_bmet_;
  mutable bool c_min_mt_bmet_;
  float min_mt_bmet_with_w_mass_;
  TBranch *b_min_mt_bmet_with_w_mass_;
  mutable bool c_min_mt_bmet_with_w_mass_;
  float mindphin_metjet_;
  TBranch *b_mindphin_metjet_;
  mutable bool c_mindphin_metjet_;
  float mj_;
  TBranch *b_mj_;
  mutable bool c_mj_;
  float mt_;
  TBranch *b_mt_;
  mutable bool c_mt_;
  float mt_reliso_;
  TBranch *b_mt_reliso_;
  mutable bool c_mt_reliso_;
  float ntrupv_mean_;
  TBranch *b_ntrupv_mean_;
  mutable bool c_ntrupv_mean_;
  float st_;
  TBranch *b_st_;
  mutable bool c_st_;
  float st_reliso_;
  TBranch *b_st_reliso_;
  mutable bool c_st_reliso_;
  float weight_;
  TBranch *b_weight_;
  mutable bool c_weight_;
  int event_;
  TBranch *b_event_;
  mutable bool c_event_;
  int lumiblock_;
  TBranch *b_lumiblock_;
  mutable bool c_lumiblock_;
  int nbl_;
  TBranch *b_nbl_;
  mutable bool c_nbl_;
  int nbm_;
  TBranch *b_nbm_;
  mutable bool c_nbm_;
  int nbt_;
  TBranch *b_nbt_;
  mutable bool c_nbt_;
  int nels_;
  TBranch *b_nels_;
  mutable bool c_nels_;
  int nels_reliso_;
  TBranch *b_nels_reliso_;
  mutable bool c_nels_reliso_;
  int nfjets_;
  TBranch *b_nfjets_;
  mutable bool c_nfjets_;
  int njets_;
  TBranch *b_njets_;
  mutable bool c_njets_;
  int nleps_;
  TBranch *b_nleps_;
  mutable bool c_nleps_;
  int nleps_reliso_;
  TBranch *b_nleps_reliso_;
  mutable bool c_nleps_reliso_;
  int nmus_;
  TBranch *b_nmus_;
  mutable bool c_nmus_;
  int nmus_reliso_;
  TBranch *b_nmus_reliso_;
  mutable bool c_nmus_reliso_;
  int npv_;
  TBranch *b_npv_;
  mutable bool c_npv_;
  int ntks_;
  TBranch *b_ntks_;
  mutable bool c_ntks_;
  int ntks_chg_;
  TBranch *b_ntks_chg_;
  mutable bool c_ntks_chg_;
  int ntks_chg_reliso_;
  TBranch *b_ntks_chg_reliso_;
  mutable bool c_ntks_chg_reliso_;
  int ntrupv_;
  TBranch *b_ntrupv_;
  mutable bool c_ntrupv_;
  int nvels_;
  TBranch *b_nvels_;
  mutable bool c_nvels_;
  int nvels_reliso_;
  TBranch *b_nvels_reliso_;
  mutable bool c_nvels_reliso_;
  int nvmus_;
  TBranch *b_nvmus_;
  mutable bool c_nvmus_;
  int nvmus_reliso_;
  TBranch *b_nvmus_reliso_;
  mutable bool c_nvmus_reliso_;
  int run_;
  TBranch *b_run_;
  mutable bool c_run_;
  std::vector<bool> els_ispf_;
  std::vector<bool> *p_els_ispf_;
  TBranch *b_els_ispf_;
  mutable bool c_els_ispf_;
  std::vector<bool> els_sigid_;
  std::vector<bool> *p_els_sigid_;
  TBranch *b_els_sigid_;
  mutable bool c_els_sigid_;
  std::vector<bool> els_tru_tm_;
  std::vector<bool> *p_els_tru_tm_;
  TBranch *b_els_tru_tm_;
  mutable bool c_els_tru_tm_;
  std::vector<bool> mus_sigid_;
  std::vector<bool> *p_mus_sigid_;
  TBranch *b_mus_sigid_;
  mutable bool c_mus_sigid_;
  std::vector<bool> mus_tru_tm_;
  std::vector<bool> *p_mus_tru_tm_;
  TBranch *b_mus_tru_tm_;
  mutable bool c_mus_tru_tm_;
  std::vector<bool> tks_from_tau_;
  std::vector<bool> *p_tks_from_tau_;
  TBranch *b_tks_from_tau_;
  mutable bool c_tks_from_tau_;
  std::vector<bool> tks_from_tauhad_;
  std::vector<bool> *p_tks_from_tauhad_;
  TBranch *b_tks_from_tauhad_;
  mutable bool c_tks_from_tauhad_;
  std::vector<bool> tks_from_taulep_;
  std::vector<bool> *p_tks_from_taulep_;
  TBranch *b_tks_from_taulep_;
  mutable bool c_tks_from_taulep_;
  std::vector<bool> tks_from_w_;
  std::vector<bool> *p_tks_from_w_;
  TBranch *b_tks_from_w_;
  mutable bool c_tks_from_w_;
  std::vector<bool> tks_is_primary_;
  std::vector<bool> *p_tks_is_primary_;
  TBranch *b_tks_is_primary_;
  mutable bool c_tks_is_primary_;
  std::vector<bool> tks_is_primary_reliso_;
  std::vector<bool> *p_tks_is_primary_reliso_;
  TBranch *b_tks_is_primary_reliso_;
  mutable bool c_tks_is_primary_reliso_;
  std::vector<bool> tks_is_sig_lep_;
  std::vector<bool> *p_tks_is_sig_lep_;
  TBranch *b_tks_is_sig_lep_;
  mutable bool c_tks_is_sig_lep_;
  std::vector<float> els_d0_;
  std::vector<float> *p_els_d0_;
  TBranch *b_els_d0_;
  mutable bool c_els_d0_;
  std::vector<float> els_dz_;
  std::vector<float> *p_els_dz_;
  TBranch *b_els_dz_;
  mutable bool c_els_dz_;
  std::vector<float> els_eta_;
  std::vector<float> *p_els_eta_;
  TBranch *b_els_eta_;
  mutable bool c_els_eta_;
  std::vector<float> els_miniso_10_;
  std::vector<float> *p_els_miniso_10_;
  TBranch *b_els_miniso_10_;
  mutable bool c_els_miniso_10_;
  std::vector<float> els_miniso_10_ch_;
  std::vector<float> *p_els_miniso_10_ch_;
  TBranch *b_els_miniso_10_ch_;
  mutable bool c_els_miniso_10_ch_;
  std::vector<float> els_miniso_10_pfpu_;
  std::vector<float> *p_els_miniso_10_pfpu_;
  TBranch *b_els_miniso_10_pfpu_;
  mutable bool c_els_miniso_10_pfpu_;
  std::vector<float> els_miniso_tr10_;
  std::vector<float> *p_els_miniso_tr10_;
  TBranch *b_els_miniso_tr10_;
  mutable bool c_els_miniso_tr10_;
  std::vector<float> els_miniso_tr10_ch_;
  std::vector<float> *p_els_miniso_tr10_ch_;
  TBranch *b_els_miniso_tr10_ch_;
  mutable bool c_els_miniso_tr10_ch_;
  std::vector<float> els_miniso_tr10_pfpu_;
  std::vector<float> *p_els_miniso_tr10_pfpu_;
  TBranch *b_els_miniso_tr10_pfpu_;
  mutable bool c_els_miniso_tr10_pfpu_;
  std::vector<float> els_mt_;
  std::vector<float> *p_els_mt_;
  TBranch *b_els_mt_;
  mutable bool c_els_mt_;
  std::vector<float> els_phi_;
  std::vector<float> *p_els_phi_;
  TBranch *b_els_phi_;
  mutable bool c_els_phi_;
  std::vector<float> els_pt_;
  std::vector<float> *p_els_pt_;
  TBranch *b_els_pt_;
  mutable bool c_els_pt_;
  std::vector<float> els_reliso_;
  std::vector<float> *p_els_reliso_;
  TBranch *b_els_reliso_;
  mutable bool c_els_reliso_;
  std::vector<float> els_reliso_r01_;
  std::vector<float> *p_els_reliso_r01_;
  TBranch *b_els_reliso_r01_;
  mutable bool c_els_reliso_r01_;
  std::vector<float> els_reliso_r015_;
  std::vector<float> *p_els_reliso_r015_;
  TBranch *b_els_reliso_r015_;
  mutable bool c_els_reliso_r015_;
  std::vector<float> els_reliso_r02_;
  std::vector<float> *p_els_reliso_r02_;
  TBranch *b_els_reliso_r02_;
  mutable bool c_els_reliso_r02_;
  std::vector<float> els_reliso_r03_;
  std::vector<float> *p_els_reliso_r03_;
  TBranch *b_els_reliso_r03_;
  mutable bool c_els_reliso_r03_;
  std::vector<float> els_reliso_r04_;
  std::vector<float> *p_els_reliso_r04_;
  TBranch *b_els_reliso_r04_;
  mutable bool c_els_reliso_r04_;
  std::vector<float> els_tru_dr_;
  std::vector<float> *p_els_tru_dr_;
  TBranch *b_els_tru_dr_;
  mutable bool c_els_tru_dr_;
  std::vector<float> fjets_eta_;
  std::vector<float> *p_fjets_eta_;
  TBranch *b_fjets_eta_;
  mutable bool c_fjets_eta_;
  std::vector<float> fjets_m_;
  std::vector<float> *p_fjets_m_;
  TBranch *b_fjets_m_;
  mutable bool c_fjets_m_;
  std::vector<float> fjets_nconst_;
  std::vector<float> *p_fjets_nconst_;
  TBranch *b_fjets_nconst_;
  mutable bool c_fjets_nconst_;
  std::vector<float> fjets_phi_;
  std::vector<float> *p_fjets_phi_;
  TBranch *b_fjets_phi_;
  mutable bool c_fjets_phi_;
  std::vector<float> fjets_pt_;
  std::vector<float> *p_fjets_pt_;
  TBranch *b_fjets_pt_;
  mutable bool c_fjets_pt_;
  std::vector<float> jets_csv_;
  std::vector<float> *p_jets_csv_;
  TBranch *b_jets_csv_;
  mutable bool c_jets_csv_;
  std::vector<float> jets_eta_;
  std::vector<float> *p_jets_eta_;
  TBranch *b_jets_eta_;
  mutable bool c_jets_eta_;
  std::vector<float> jets_id_;
  std::vector<float> *p_jets_id_;
  TBranch *b_jets_id_;
  mutable bool c_jets_id_;
  std::vector<float> jets_islep_;
  std::vector<float> *p_jets_islep_;
  TBranch *b_jets_islep_;
  mutable bool c_jets_islep_;
  std::vector<float> jets_phi_;
  std::vector<float> *p_jets_phi_;
  TBranch *b_jets_phi_;
  mutable bool c_jets_phi_;
  std::vector<float> jets_pt_;
  std::vector<float> *p_jets_pt_;
  TBranch *b_jets_pt_;
  mutable bool c_jets_pt_;
  std::vector<float> mc_eta_;
  std::vector<float> *p_mc_eta_;
  TBranch *b_mc_eta_;
  mutable bool c_mc_eta_;
  std::vector<float> mc_phi_;
  std::vector<float> *p_mc_phi_;
  TBranch *b_mc_phi_;
  mutable bool c_mc_phi_;
  std::vector<float> mc_pt_;
  std::vector<float> *p_mc_pt_;
  TBranch *b_mc_pt_;
  mutable bool c_mc_pt_;
  std::vector<float> mus_d0_;
  std::vector<float> *p_mus_d0_;
  TBranch *b_mus_d0_;
  mutable bool c_mus_d0_;
  std::vector<float> mus_dz_;
  std::vector<float> *p_mus_dz_;
  TBranch *b_mus_dz_;
  mutable bool c_mus_dz_;
  std::vector<float> mus_eta_;
  std::vector<float> *p_mus_eta_;
  TBranch *b_mus_eta_;
  mutable bool c_mus_eta_;
  std::vector<float> mus_miniso_10_;
  std::vector<float> *p_mus_miniso_10_;
  TBranch *b_mus_miniso_10_;
  mutable bool c_mus_miniso_10_;
  std::vector<float> mus_miniso_10_ch_;
  std::vector<float> *p_mus_miniso_10_ch_;
  TBranch *b_mus_miniso_10_ch_;
  mutable bool c_mus_miniso_10_ch_;
  std::vector<float> mus_miniso_10_pfpu_;
  std::vector<float> *p_mus_miniso_10_pfpu_;
  TBranch *b_mus_miniso_10_pfpu_;
  mutable bool c_mus_miniso_10_pfpu_;
  std::vector<float> mus_miniso_tr10_;
  std::vector<float> *p_mus_miniso_tr10_;
  TBranch *b_mus_miniso_tr10_;
  mutable bool c_mus_miniso_tr10_;
  std::vector<float> mus_miniso_tr10_ch_;
  std::vector<float> *p_mus_miniso_tr10_ch_;
  TBranch *b_mus_miniso_tr10_ch_;
  mutable bool c_mus_miniso_tr10_ch_;
  std::vector<float> mus_miniso_tr10_pfpu_;
  std::vector<float> *p_mus_miniso_tr10_pfpu_;
  TBranch *b_mus_miniso_tr10_pfpu_;
  mutable bool c_mus_miniso_tr10_pfpu_;
  std::vector<float> mus_mt_;
  std::vector<float> *p_mus_mt_;
  TBranch *b_mus_mt_;
  mutable bool c_mus_mt_;
  std::vector<float> mus_phi_;
  std::vector<float> *p_mus_phi_;
  TBranch *b_mus_phi_;
  mutable bool c_mus_phi_;
  std::vector<float> mus_pt_;
  std::vector<float> *p_mus_pt_;
  TBranch *b_mus_pt_;
  mutable bool c_mus_pt_;
  std::vector<float> mus_reliso_;
  std::vector<float> *p_mus_reliso_;
  TBranch *b_mus_reliso_;
  mutable bool c_mus_reliso_;
  std::vector<float> mus_reliso_r01_;
  std::vector<float> *p_mus_reliso_r01_;
  TBranch *b_mus_reliso_r01_;
  mutable bool c_mus_reliso_r01_;
  std::vector<float> mus_reliso_r015_;
  std::vector<float> *p_mus_reliso_r015_;
  TBranch *b_mus_reliso_r015_;
  mutable bool c_mus_reliso_r015_;
  std::vector<float> mus_reliso_r02_;
  std::vector<float> *p_mus_reliso_r02_;
  TBranch *b_mus_reliso_r02_;
  mutable bool c_mus_reliso_r02_;
  std::vector<float> mus_reliso_r03_;
  std::vector<float> *p_mus_reliso_r03_;
  TBranch *b_mus_reliso_r03_;
  mutable bool c_mus_reliso_r03_;
  std::vector<float> mus_reliso_r04_;
  std::vector<float> *p_mus_reliso_r04_;
  TBranch *b_mus_reliso_r04_;
  mutable bool c_mus_reliso_r04_;
  std::vector<float> mus_tru_dr_;
  std::vector<float> *p_mus_tru_dr_;
  TBranch *b_mus_tru_dr_;
  mutable bool c_mus_tru_dr_;
  std::vector<float> tks_eta_;
  std::vector<float> *p_tks_eta_;
  TBranch *b_tks_eta_;
  mutable bool c_tks_eta_;
  std::vector<float> tks_mini_ch_;
  std::vector<float> *p_tks_mini_ch_;
  TBranch *b_tks_mini_ch_;
  mutable bool c_tks_mini_ch_;
  std::vector<float> tks_mini_ne_;
  std::vector<float> *p_tks_mini_ne_;
  TBranch *b_tks_mini_ne_;
  mutable bool c_tks_mini_ne_;
  std::vector<float> tks_mt_;
  std::vector<float> *p_tks_mt_;
  TBranch *b_tks_mt_;
  mutable bool c_tks_mt_;
  std::vector<float> tks_phi_;
  std::vector<float> *p_tks_phi_;
  TBranch *b_tks_phi_;
  mutable bool c_tks_phi_;
  std::vector<float> tks_pt_;
  std::vector<float> *p_tks_pt_;
  TBranch *b_tks_pt_;
  mutable bool c_tks_pt_;
  std::vector<float> tks_r02_ch_;
  std::vector<float> *p_tks_r02_ch_;
  TBranch *b_tks_r02_ch_;
  mutable bool c_tks_r02_ch_;
  std::vector<float> tks_r02_ne_;
  std::vector<float> *p_tks_r02_ne_;
  TBranch *b_tks_r02_ne_;
  mutable bool c_tks_r02_ne_;
  std::vector<float> tks_r03_ch_;
  std::vector<float> *p_tks_r03_ch_;
  TBranch *b_tks_r03_ch_;
  mutable bool c_tks_r03_ch_;
  std::vector<float> tks_r03_ne_;
  std::vector<float> *p_tks_r03_ne_;
  TBranch *b_tks_r03_ne_;
  mutable bool c_tks_r03_ne_;
  std::vector<float> tks_tru_dp_;
  std::vector<float> *p_tks_tru_dp_;
  TBranch *b_tks_tru_dp_;
  mutable bool c_tks_tru_dp_;
  std::vector<float> tks_tru_dr_;
  std::vector<float> *p_tks_tru_dr_;
  TBranch *b_tks_tru_dr_;
  mutable bool c_tks_tru_dr_;
  std::vector<int> els_charge_;
  std::vector<int> *p_els_charge_;
  TBranch *b_els_charge_;
  mutable bool c_els_charge_;
  std::vector<int> els_tru_id_;
  std::vector<int> *p_els_tru_id_;
  TBranch *b_els_tru_id_;
  mutable bool c_els_tru_id_;
  std::vector<int> els_tru_momid_;
  std::vector<int> *p_els_tru_momid_;
  TBranch *b_els_tru_momid_;
  mutable bool c_els_tru_momid_;
  std::vector<int> mc_id_;
  std::vector<int> *p_mc_id_;
  TBranch *b_mc_id_;
  mutable bool c_mc_id_;
  std::vector<int> mc_status_;
  std::vector<int> *p_mc_status_;
  TBranch *b_mc_status_;
  mutable bool c_mc_status_;
  std::vector<int> mus_charge_;
  std::vector<int> *p_mus_charge_;
  TBranch *b_mus_charge_;
  mutable bool c_mus_charge_;
  std::vector<int> mus_tru_id_;
  std::vector<int> *p_mus_tru_id_;
  TBranch *b_mus_tru_id_;
  mutable bool c_mus_tru_id_;
  std::vector<int> mus_tru_momid_;
  std::vector<int> *p_mus_tru_momid_;
  TBranch *b_mus_tru_momid_;
  mutable bool c_mus_tru_momid_;
  std::vector<int> tks_from_pv_;
  std::vector<int> *p_tks_from_pv_;
  TBranch *b_tks_from_pv_;
  mutable bool c_tks_from_pv_;
  std::vector<int> tks_id_;
  std::vector<int> *p_tks_id_;
  TBranch *b_tks_id_;
  mutable bool c_tks_id_;
  std::vector<int> tks_num_prongs_;
  std::vector<int> *p_tks_num_prongs_;
  TBranch *b_tks_num_prongs_;
  mutable bool c_tks_num_prongs_;
  std::vector<int> tks_tru_id_;
  std::vector<int> *p_tks_tru_id_;
  TBranch *b_tks_tru_id_;
  mutable bool c_tks_tru_id_;
  std::vector<size_t> mc_mom_;
  std::vector<size_t> *p_mc_mom_;
  TBranch *b_mc_mom_;
  mutable bool c_mc_mom_;
  unsigned mc_type_;
  TBranch *b_mc_type_;
  mutable bool c_mc_type_;
};

small_tree* NewTree(const std::type_info &type);

#include "small_tree_quick.hpp"

#endif
